---
openapi: 3.0.3

info:
  title: Subscription Notification API
  version: 1.0.1
  description: >
    API for handling subscription notifications. Called on a regular basis to inform about updates to your subscriptions.
    This API is called by Hapag-Lloyd's systems and needs to be implemented by you to receive subscription notifications.

    In case no changes occurred since the last notification, no call will be made.
paths:
  /notify:
    post:
      summary: |
        Receive subscription notification. The data is sent as JSON and might compressed. Check the "Content-Encoding" header.
      tags:
        - RateSheetSubscriptionNotification
      description: Endpoint to receive subscription notifications.
      operationId: notify
      parameters:
        - in: header
          name: X-API-Version
          required: true
          schema:
            type: string
            example: 1, 2, 3
          description: The API version the client is using.
        - in: header
          name: X-API-Key
          required: true
          schema:
            type: string
          description:
            Unique identifier for the client sending the notification. This is the secret used when the subscription
            was created.
        - in: header
          name: X-Request-ID
          required: true
          schema:
            type: string
          description: Unique identifier for the request. UUID format.
        - in: header
          name: X-Idempotency-Key
          required: true
          schema:
            type: string
          description: Unique identifier for the idempotent request. UUID format and valid for 23 hours.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriptionNotification"
      responses:
        "200":
          description: Notification received successfully
        "400":
          description: Bad request
        "500":
          description: Internal server error
components:
  schemas:
    SubscriptionNotification:
      type: object
      properties:
        subscription_id:
          type: string
          description: Unique identifier for the subscription assigned by Hapag-Lloyd.
        marketing_routing_party_name:
          type: string
          minLength: 1
          maxLength: 6
          description: |
            The Marketing Routing Party (MR) is the party that designates Hapag-Lloyd as the carrier for the shipment.
            MR consists of name and supplement. This field represents the name part of the Marketing Routing Party.
        marketing_routing_party_supplement:
          type: integer
          minimum: 1
          maximum: 999
          description: The numerical part of Marketing Routing Party (supplement).
        commercial_reference:
          type: string
          description: "Commercial reference: either a quotation number or a contract number"
          example: W230201784558
        routings:
          type: array
          items:
            $ref: "#/components/schemas/Routing"
      required:
        - subscription_id
        - marketing_routing_party_name
        - marketing_routing_party_supplement
        - commercial_reference
        - routings
    Location:
      type: object
      description: A specific location identified by country and optionally a locode. The country is always present.
      properties:
        locode:
          type: string
        country:
          type: string
      required:
        - country

    Routing:
      type: object
      properties:
        places_of_receipt:
          type: array
          items:
            $ref: "#/components/schemas/Location"
        places_of_delivery:
          type: array
          items:
            $ref: "#/components/schemas/Location"
        equipments:
          type: object
          properties:
            container_types:
              type: array
              items:
                type: string
                example: 20GP, 40HC, 42GP
            rates:
              type: array
              description:
                List of rates changed. maximum_valid_to_date and maximum_valid_to_date define the maximum validity
                period of the rate.
              items:
                type: object
                properties:
                  charge_code:
                    type: string
                    description: Three-letter-code of a charge type.
                    example: BAF, CAF, SEA
                  minimum_valid_from_date:
                    type: string
                    format: date
                  maximum_valid_to_date:
                    type: string
                    format: date
                required:
                  - charge_code
                  - minimum_valid_from_date
                  - maximum_valid_to_date
      required:
        - place_of_receipt
        - place_of_delivery
